export default {
    DAYS_REQUEST_DAYS: 'DAYS_REQUEST_DAYS',
    DAYS_WEEK_PLANS_RECEIVED: 'DAYS_WEEK_PLANS_RECEIVED',
    WEEK_ITEMS_RECEIVED: 'WEEK_ITEMS_RECEIVED',
    WEEK_DAY_SELECTED: 'WEEK_DAY_SELECTED',
    DAYS_DAY_SUMMARY_RECEIVED: 'DAYS_DAY_SUMMARY_RECEIVED',
    DAYS_WEEK_SUMMARY_RECEIVED: 'DAYS_WEEK_SUMMARY_RECEIVED'
}