export default {
    CREATE_REQUESTED: 'CREATE_REQUESTED',
    CREATE_MEAL_REQUESTED: 'CREATE_MEAL_REQUESTED',
    CREATE_MEAL_SUCCESSFUL: 'CREATE_MEAL_SUCCESSFUL',
    CREATE_SUCCESSFUL: 'CREATE_SUCCESSFUL'
}