export default {
    USER_CHANGE_VALUE: 'USER_CHANGE_VALUE',
    USER_FETCH_USER: 'USER_FETCH_USER',
    USER_USER_RECEIVED: 'USER_USER_RECEIVED',
    USER_REQUEST_USER_SAVE: 'USER_REQUEST_USER_SAVE',
    USER_REQUEST_DAY_SAVE: 'USER_REQUEST_DAY_SAVE'
}