export default {
    NEW_DAY_GRAMS_CHANGE: 'NEW_DAY_GRAMS_CHANGE',
    NEW_DAY_DURATION_CHANGE: 'NEW_DAY_DURATION_CHANGE',
    NEW_DAY_SPEED_CHANGE: 'NEW_DAY_SPEED_CHANGE',
    MEAL_FAVORITE_TOGGLE_REQUESTED: 'MEAL_FAVORITE_TOGGLE_REQUESTED',
}