export default {
    ADMIN_REQUEST_UPDATE_VALUE: 'ADMIN_REQUEST_UPDATE_VALUE',
    ADMIN_UPDATE_SUCCESSFUL: 'ADMIN_UPDATE_SUCCESSFUL',
    ADMIN_REQUEST_DELETE: 'ADMIN_REQUEST_DELETE',
    ADMIN_DELETE_SUCCESSFUL: 'ADMIN_DELETE_SUCCESSFUL'
}